config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :tweets, only: [:create, :destroy]

  resources :usernames, only: [:new, :update]

  get :dashboard, to: 'dashboard#index'

  root "home#index"


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: { case_sensitive: false }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_to_username_form, if: -> { user_signed_in? && current_user.username.blank? }
  protected

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  def redirect_to_username_form

    redirect_to new_username_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.new(tweet_params.merge(user: current_user))
    if tweet.save
      redirect_to dashboard_path
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to dashboard_path
  end

def show
end

  private
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
  before_action :authenticate_user!
skip_before_action :redirect_to_username_form

def new
end

def update

if username_params[:username].present? && current_user.update(username_params)
  redirect_to dashboard_path
else
  flash[:alert] = if username_params[:username].blank?
                    "Please set a username"
  else
    current_user.errors.full_messages.join(", ")
  end
redirect_to new_username_path
end
end

private

def username_params
  params.require(:user).permit(:username)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/index.html.erb
    <h1>Logged in!</h1>
    <%= link_to "Log Out", destroy_user_session_path, data: {
            turbo_method: :delete}, class: "btn btn-primary btn-md" %>

    <%= form_with model: Tweet.new, url: tweets_path, method: :post, local: true do |f|  %>
        <%= f.text_field :body %>
        <%= f.submit %>
    <% end %>

    <ul>
        <% Tweet.find_each do |tweet| %>
            <li>
                <%= tweet.body %>
                <%= link_to "delete", tweet_path(tweet.id), data: {
            turbo_method: :delete } %>
            </li>
        <% end %>
    </ul>

app/views/home/index.html.erb
<h1>Hello</h1>
<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-md" %> 
<%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary btn-,d" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if flash.any? %>
      <%= render "shared/flashes" %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 rounded-0 text-center" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 rounded-0 text-center" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      
    </button>
  </div>
<% end %>

app/views/usernames/new.html.erb
<div class="container py-5" style="max-width: 540px">
  <h2>Set your Username</h2>

  <%= form_with model: current_user, local: true, url: username_path(current_user) do |f| %>
    <div class = "mb-3">

        <%= f.label :username, class: "form-label" %>
        <%= f.text_field :username, class: "form-control"%>

    </div>

    <%= f.submit "Set username", class: "btn btn-primary"%>

  <% end %>


</div>

